name: Unit Testing
on: [push, pull_request]
jobs:
  my-job:
    name: breadroll Test Suite
    runs-on: ubuntu-latest
    steps:
      # ...
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.22 

      # run any `bun` or `bunx` command
      - run: bun install
      - run: bun test