export type Cities = {
  id: string;
  name: string;
  state_id: string;
  state_code: string;
  state_name: string;
  country_id: string;
  country_code: string;
  country_name: string;
  latitude: string;
  longitude: string;
  wikiDataId: string;
};

export type CKD = {
  id: string;
  age: string;
  bp: string;
  sg: string;
  al: string;
  su: string;
  rbc: object;
  pc: string;
  pcc: string;
  ba: string;
  bgr: string;
  bu: string;
  sc: string;
  sod: object;
  pot: object;
  hemo: string;
  pcv: string;
  wbcc: string;
  rbcc: string;
  htn: string;
  dm: string;
  cad: string;
  appet: string;
  pe: string;
  ane: string;
  class: string;
};
