export type Cities = {
  id: string;
  name: string;
  state_id: string;
  state_code: string;
  state_name: string;
  country_id: string;
  country_code: string;
  country_name: string;
  latitude: string;
  longitude: string;
  wikiDataId: string;
};

export type CKDNoParse = {
  id: string;
  age: string;
  bp: string;
  sg: string;
  al: string;
  su: string;
  rbc: object;
  pc: string;
  pcc: string;
  ba: string;
  bgr: string;
  bu: string;
  sc: string;
  sod: object;
  pot: object;
  hemo: string;
  pcv: string;
  wbcc: string;
  rbcc: string;
  htn: string;
  dm: string;
  cad: string;
  appet: string;
  pe: string;
  ane: string;
  class: string;
};

export type CKD = {
  id: number;
  age: number;
  bp: number;
  sg: number;
  al: number;
  su: number;
  rbc: object;
  pc: string;
  pcc: string;
  ba: string;
  bgr: number;
  bu: number;
  sc: number;
  sod: object;
  pot: object;
  hemo: number;
  pcv: number;
  wbcc: number;
  rbcc: number;
  htn: string;
  dm: string;
  cad: string;
  appet: string;
  pe: string;
  ane: string;
  class: string;
};
